# Project-wide Gradle settings.
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX — required when using core-ktx, material, viewmodel, etc.
android.useAndroidX=true
android.enableJetifier=true

# Android SDK — override in local.properties if not in default location
# sdk.dir=/home/ojinguh/android-sdk
